# Generated by Django 4.2.13 on 2024-06-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='name',
            new_name='fac_name',
        ),
    ]
