# Generated by Django 4.2.13 on 2024-05-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital_app', '0002_alter_patient_phone_number_alter_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='name',
        ),
    ]
