# Generated by Django 4.2.13 on 2024-05-29 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital_app', '0003_rename_user_doctor_name_rename_user_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doc_name',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient',
            field=models.OneToOneField(default=1234, on_delete=django.db.models.deletion.CASCADE, to='ehospital_app.patient'),
            preserve_default=False,
        ),
    ]
