# Generated by Django 4.2.13 on 2024-05-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital_app', '0004_remove_doctor_name_doctor_doc_name_doctor_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patient',
        ),
    ]
